### ISSUE TITLE
RFC: Configuring schema from js script

### ISSUE THREAD

**Issue by freshollie** [0no-co/gql.tada#87]
## Summary

My setup currently uses a codegen configuration which is able to read my schema from the output of a JS script rather than a schema SDL:

codegen.yml
```yaml
schema:
  - "./codegen.schema.js"
generates:
  ./schema.graphql:
    plugins:
      - schema-ast
    config:
      includeDirectives: true
```

codegen.schema.js
```js

module.exports = require("./src/shared/backend/graph").schema;
```

The outputted `schema.graphql` is currently able to be read by this plugin, however it would be nice if the intermediate step of writing the schema object to graphql AST was not necessary.

## Proposed Solution

```json
    "plugins": [
      {
        "name": "@0no-co/graphqlsp",
        "schema": "./codegen.schema.js",
        "tadaOutputLocation": "./src/graphql-env.d.ts"
      }
    ]
```

## Requirements

The plugin just needs to be able to read the schema from the JS output in the type `GraphQLSchema`
